---
title: "HRExcercise-Data"
output: html_document
---



----

## Data

Load data.

```{r}
HRExercise <- read_csv("HRExercise.csv", 
    col_types = cols(Date = col_date(format = "%m/%d/%y"), 
        Time = col_time(format = "%T"), DateTime = col_datetime(format = "%m/%d/%y %T"), 
        Exercise = col_factor(levels = c("Yoga", "Walking", "Running", "Biking", "Trail Walking", "Trail Running", "Mountain Biking")), 
        ExerciseValue = col_factor(levels = c("0", "1", "2", "3", "4", "5", "6")), 
        Course = col_factor(levels = c("Alta Vista", 
            "Deer Hollow", "Enterprise South", 
            "Four Pass Loop", "Full Practice", 
            "Greenway", "Hawk's Ridge", "Montreat", 
            "Montreat Trails", "Restorative", 
            "Riverwalk", "Southern Soul", 
            "Stringers", "White Oak - Green", 
            "White Sands Cove", "Whole Enchilada", "Former Three")), 
        CourseValue = col_factor(levels = c("0", "1", "2", "3")),
        Zone = col_factor(levels = c("1", "2", "3", "4", "5")),
        IsYoga = col_factor(levels = c("0", "1")), 
        IsFullPractice = col_factor(levels = c("0", "1")), 
        IsSouthernSoul = col_factor(levels = c("0", "1")), 
        IsOtherYoga = col_factor(levels = c("0", "1")), 
        IsLessThan12HoursSinceLastYoga = col_factor(levels = c("0", "1")), 
        IsLessThan24HoursSinceLastYoga = col_factor(levels = c("0", "1")), 
        IsLessThan36HoursSinceLastYoga = col_factor(levels = c("0", "1")), 
        IsLessThan48HoursSinceLastYoga = col_factor(levels = c("0", "1")), 
        IsLessThan60HoursSinceLastYoga = col_factor(levels = c("0", "1")), 
        IsLessThan72HoursSinceLastYoga = col_factor(levels = c("0", "1")), 
        IsBiking = col_factor(levels = c("0", "1")), 
        IsBikingAtWhiteOakGreen = col_factor(levels = c("0", "1")), 
        IsBikingAtWholeEnchilada = col_factor(levels = c("0", "1")), 
        IsBikingAtStringers = col_factor(levels = c("0", "1")), 
        IsBikingAtRiverwalk = col_factor(levels = c("0", "1")),
        IsBikingAtGreenway = col_factor(levels = c("0", "1")),
        IsOtherBiking = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastBiking = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastBiking = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastBiking = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastBiking = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastBiking = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastBiking = col_factor(levels = c("0", "1")),
        IsWalking = col_factor(levels = c("0", "1")),
        IsWalkingAtHawksRidge = col_factor(levels = c("0", "1")),
        IsWalkingAtFourPassLoop = col_factor(levels = c("0", "1")),
        IsWalkingAtRiverwalk = col_factor(levels = c("0", "1")),
        IsOtherWalking = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastWalking = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastWalking = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastWalking = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastWalking = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastWalking = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastWalking = col_factor(levels = c("0", "1")),
        IsRunning = col_factor(levels = c("0", "1")),
        IsRunningAtHawksRidge = col_factor(levels = c("0", "1")),
        IsRunningAtStringers = col_factor(levels = c("0", "1")),
        IsRunningAtRiverwalk = col_factor(levels = c("0", "1")),
        IsOtherRunning = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastRunning = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastRunning = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastRunning = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastRunning = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastRunning = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastRunning = col_factor(levels = c("0", "1")),
        IsHawksRidge = col_factor(levels = c("0", "1")),
        IsRiverwalk = col_factor(levels = c("0", "1")),
        IsWholeEnchilada = col_factor(levels = c("0", "1")),
        IsWhiteOakGreen = col_factor(levels = c("0", "1")),
        IsStringers = col_factor(levels = c("0", "1")),
        IsZone1 = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastZone1 = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastZone1 = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastZone1 = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastZone1 = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastZone1 = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastZone1 = col_factor(levels = c("0", "1")),
        IsZone2 = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastZone2 = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastZone2 = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastZone2 = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastZone2 = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastZone2 = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastZone2 = col_factor(levels = c("0", "1")),
        IsZone3 = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastZone3 = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastZone3 = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastZone3 = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastZone3 = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastZone3 = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastZone3 = col_factor(levels = c("0", "1")),
        IsZone4 = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastZone4 = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastZone4 = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastZone4 = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastZone4 = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastZone4 = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastZone4 = col_factor(levels = c("0", "1")),
        IsZone5 = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastZone5 = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastZone5 = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastZone5 = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastZone5 = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastZone5 = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastZone5 = col_factor(levels = c("0", "1")),
        IsLessThan12HoursSinceLastAnything = col_factor(levels = c("0", "1")),
        IsLessThan24HoursSinceLastAnything = col_factor(levels = c("0", "1")),
        IsLessThan36HoursSinceLastAnything = col_factor(levels = c("0", "1")),
        IsLessThan48HoursSinceLastAnything = col_factor(levels = c("0", "1")),
        IsLessThan60HoursSinceLastAnything = col_factor(levels = c("0", "1")),
        IsLessThan72HoursSinceLastAnything = col_factor(levels = c("0", "1"))
        ))
```


View the data and list any problems.

```{r}
HRExercise
if (exists('problems')) {
  problems(HRExercise)
}
```


Create any necessary time series data objects (based on final formula below).

```{r}
lag <- 1

efficiency <- data.frame(HRExercise$Efficiency)
efficiency_lag <- ts(data = efficiency[1:(nrow(efficiency) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)
efficiency <- ts(data = efficiency[(lag + 1):(nrow(efficiency) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

bpm <- data.frame(HRExercise$BPM)
bpm_lag <- ts(data = bpm[1:(nrow(bpm) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)
bpm <- ts(data = bpm[(lag + 1):(nrow(bpm) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

caloriespermin <- data.frame(HRExercise$CaloriesPerMin)
caloriespermin_lag <- ts(data = caloriespermin[1:(nrow(caloriespermin) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)
caloriespermin <- ts(data = caloriespermin[(lag + 1):(nrow(caloriespermin) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

calories <- data.frame(HRExercise$Calories)
calories <- ts(data = calories[(lag + 1):(nrow(calories) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

timeinmin <- data.frame(HRExercise$TimeInMin)
timeinmin <- ts(data = timeinmin[(lag + 1):(nrow(timeinmin) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

elevationchangeinfeetpermin <- data.frame(HRExercise$ElevationChangeInFeetPerMin)
elevationchangeinfeetpermin <- ts(data = elevationchangeinfeetpermin[(lag + 1):(nrow(elevationchangeinfeetpermin) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

elevationchangeinfeet <- data.frame(HRExercise$ElevationChangeInFeet)
elevationchangeinfeet <- ts(data = elevationchangeinfeet[(lag + 1):(nrow(elevationchangeinfeet) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

distanceinfeetpermin <- data.frame(HRExercise$DistanceInFeetPerMin)
distanceinfeetpermin <- ts(data = distanceinfeetpermin[(lag + 1):(nrow(distanceinfeetpermin) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

distanceinfeet <- data.frame(HRExercise$DistanceInFeet)
distanceinfeet <- ts(data = distanceinfeet[(lag + 1):(nrow(distanceinfeet) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

temp <- data.frame(HRExercise$Temp)
temp <- ts(data = temp[(lag + 1):(nrow(temp) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

dewpoint <- data.frame(HRExercise$DewPoint)
dewpoint <- ts(data = dewpoint[(lag + 1):(nrow(dewpoint) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

exercise <- data.frame(HRExercise$Exercise)
exercise <- ts(data = exercise[(lag + 1):(nrow(exercise) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

course <- data.frame(HRExercise$Course)
course <- ts(data = course[(lag + 1):(nrow(course) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

islessthan24hourssincelastanything <- data.frame(HRExercise$IsLessThan24HoursSinceLastAnything)
islessthan24hourssincelastanything <- ts(data = islessthan24hourssincelastanything[(lag + 1):(nrow(islessthan24hourssincelastanything) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

islessthan36hourssincelastanything <- data.frame(HRExercise$IsLessThan36HoursSinceLastAnything)
islessthan36hourssincelastanything <- ts(data = islessthan36hourssincelastanything[(lag + 1):(nrow(islessthan36hourssincelastanything) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)

islessthan48hourssincelastanything <- data.frame(HRExercise$IsLessThan48HoursSinceLastAnything)
islessthan48hourssincelastanything <- ts(data = islessthan48hourssincelastanything[(lag + 1):(nrow(islessthan48hourssincelastanything) - lag), ], start = 1, end = nrow(HRExercise) - lag, frequency = 1)
```


